food/food/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/',include('foodapp.urls')),
]

food/foodapp/urls.py
from django.urls import path
from .views import IngredientList,IngredientDetail
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
	# path('inglist/', views.ingredients_list, name='ingredients_list')
	path('test/', views.ing_list, name='ing_list'),
	path('test_dhruv/', views.get_food_fe, name='inge'),
	path('new/', views.food_new, name='food_new'),

	path('ing/', IngredientList.as_view(), name="ingredient_list"),
	path('ing/<int:pk>', IngredientDetail.as_view(), name="ingredient_detail"),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

food/foodapp/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.contenttypes.fields import GenericRelation
# Create your models here.
class Food(models.Model):
	food_name = models.CharField(max_length=200)
	added_date = models.DateTimeField(default=timezone.now)
	# ingredients = GenericRelation(Ingredients)
 
	def __str__(self):
		return self.food_name

class Ingredients(models.Model):
	food =models.ForeignKey(Food, on_delete=models.CASCADE, related_name='ingredientss')
	nutrients = models.CharField(max_length=200)
	value = models.IntegerField(default=0)
	unit = models.CharField(max_length=10)

	def __str__(self):
		return self.nutrients

	

food/foodapp/forms.py
from django import forms
from .models import Food,Ingredients
from django.forms.models import inlineformset_factory

FoodForm = inlineformset_factory(Food,Ingredients, fields=('food_name','added_date','nutrients','value','unit',))

# class FoodForm(forms.ModelForm):

# 	ingredient = forms.ModelChoiceField(queryset=Ingredients.objects.all())

# 	class Meta:
# 		model = Food
# 		fields = ('food_name','added_date','ingredient')
# 	

food/foodapp/views.py
from django.shortcuts import render,redirect
# from .models import Ingredients, Food
# # Create your views here.
# def ingredients_list(request):
# 	# ingrdients = Ingredients.objects.filter(food=1)
# 	food = Food.objects.filter(food_name='Biryani').first()
# 	# print(doo.food_name)
# 	# print(ingrdients.added_date)
# 	ingre = food.ingredients.all()
# 		# print(a)
	

# 	return render(request, 'ingredients_list.html', {'ingrdients':ingre,'food':food})


from .models import Ingredients,Food
from .serializers import FoodSerializer, IngredientSerializer
from rest_framework import generics
from rest_framework.renderers import TemplateHTMLRenderer
from rest_framework import filters
from .forms import FoodForm
from django.generics.edit import CreateView, UpdateView
from django.generics.list import ListView
# class IngredientList(generics.ListCreateAPIView):
# 	Model = Ingredients
# 	serializer_class = IngredientSerializer
	
# 	def get_queryset(self):
# 		queryset = Ingredients.objects.all()
# 		print(queryset)
# 		food = self.request.query_params.get('food')
# 		print(food)
		
# 		if food:
# 			queryset = queryset.filter(food_id=food)
# 		return queryset
	
	
class IngredientDetail(generics.RetrieveUpdateDestroyAPIView):
	serializer_class = FoodSerializer
	queryset = Food.objects.all()
	#template_name = 'ingredients_list.html'
	
class IngredientList(generics.ListCreateAPIView):
	search_fields = ['=food_name']
	filter_backends = (filters.SearchFilter,)
	serializer_class = FoodSerializer
	queryset = Food.objects.all()



def ing_list(request):
	foods = Food.objects.all()
	return render(request, 'foodapp/test.html', {'foods': foods})

def get_food_fe(request):
	return render(request, 'foodapp/base.html')


def food_new(request):
	if request.method == 'POST':
		form = FoodForm(request.POST)
		if form.is_valid():
			food = form.save(commit=False)
			food.save()
			return redirect('ingredient_detail', pk=food.pk)
	else:

		form = FoodForm()
	return render(request, 'foodapp/test_form.html', {'form':form})


class FoodCreateView(CreateView):
	Model = Food
	fields = ['food_name','added_date','nutrients','value','unit',]
	def get_context_data(self, **kwargs):
		# we need to overwrite get_context_data
		# to make sure that our formset is rendered
		data = super().get_context_data(**kwargs)
		if self.request.POST:
			data["ingrdientss"] = FoodForm(self.request.POST)
		else:
			data["ingrdientss"] = FoodForm()
		return data

	def form_valid(self, form):
		context = self.get_context_data()
		ingrdientss = context["ingrdientss"]
		self.object = form.save()
		if ingrdientss.is_valid():
			ingrdientss.instance = self.object
			ingrdientss.save()
		return super().form_valid(form)

food/templates/foodapp/base - Copy.html
{% load staticfiles %}

<html>
    <head>
        <title>Foodapp</title>
        <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>

    </head>

    <body>
        <label for="food_name"></label>
        <input type="text" name="food_name" id="food_name">
        <button id='btn_food_name'>GET MAGIC</button>
        <div id="output"></div>
       <!--  <hr> -->
       <!--  <div>

            <div id="food_name_val"></div>
            <div id="dets"></div>
        </div> -->
    </body>

    <body>
        <main>
            {% block content %}
                <form method="GET">
                	<select id="food-selected">
                    	{% for food in food_list %}
                       	 	<option value="{{ food.id }}">
                        		{{ food.food_name }}
                        	</option>
                    	{% endfor %}
                	</select>
                	<input type="button" value="Update" id="selection-button" method="GET">
            	</form>
            {% endblock %}    
        </main>       
    </body>
</html>

food/templates/foodapp/base.html
{% load staticfiles %}

<html>
  <head>
    <title>Foodapp</title>
    <script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
    

  </head>

  <body>
    <label for="food_name"> Enter Food: 
      <input type="text" name="food_name" id="food_name">
    </label>
    <button id='btn_food_name'>GET MAGIC</button>
    <hr>
    <div id="output"></div>
    <hr>
    <div id="food">
      food : 
    </div>
     <!--  <hr> -->
      <div>

      <div id="food_name_val"></div>
      <ul id="dets"></ul>
      <table>
        <thead>
          <tr>
            <th>col1</th>
            

          </tr>
        </thead>
        <tbody>
          
        </tbody>
      </table>
    </div>
  </body>
  <script type="text/javascript">
    $('document').ready(function() {
      $('#btn_food_name').click(function() {
        $.get('/food/ing/' + $('#food_name').val()).then(function(data){
          $('#output').append(JSON.stringify(data));
          $('#food').append(data.food_name);
          for (i in data.ingredients){
           $('tbody').append('<tr style="color:green;border:1px solid black"><td>'+JSON.stringify(data.ingredients[i])+'</td><tr>');
          }
      });
     });
      
      
      // $.ajax(url,method=get);
      // $('#btn_food_name').hover(function(){console.log('dg=dkfhd')});
    });
  </script>
</html>

food/templates/foodapp/dhruv_example.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>
<body>
<table>
	<thead></thead>
	<tbody>
		tr
	</tbody>
</table>
</body>
</html> 

food/templates/foodapp/ingredients_list.html
{% extend "base.html" %}

{% block content %}

    <script type="text/javascript">
        $.ajax({
         url: "{% url 'food/ingredient_list' %}",
         method: 'GET',
         data : {
                 filter_category: parseInt(foodSelected)
         }
         success: function(data){
             console.log(data)
         },
         error: function(xhr, errmsg, err){
             console.log("error")
             console.log(error_data)
         }
        });
    </script>
{% endblock %}

food/templates/foodapp/sitest.html
<h1>Food</h1>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <h2>ingrdientss</h2>
    {{ ingrdientss.as_p }}
    <input type="submit" value="Save">
</form>

food/templates/foodapp/test.html
{% load staticfiles %}
<html>
	<head>
		<link rel="stylesheet" href="{% static 'css/test.css' %}">
	</head>
	<body>
		<div>
            <h1><a href="/">Django CSS Testing</a></h1>
        </div>
        {% for f in foods%}
        	<div>
        		{{f.food_name}}
        		<p>{{f.added_date}}</p>
        		
        	</div>
        {% endfor %}
	</body>
</html>
	

food/templates/foodapp/test_form.html
{% load staticfiles %}

<html>
    <head>
        <title>Food app</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/test.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'food_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Django Form test</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    	<h2>New post</h2>
    					<form method="POST" class="post-form">{% csrf_token %}
       						{{ form.as_p }}
        					<button type="submit" class="save btn btn-default">Save</button>
   						</form>
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>